name: syft-sbom-ci

on:
  release:
    types: [published]
  push:
    branches:
      - 'release/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  sbom:
    uses: mozilla/ssdlc-actions/.github/workflows/syft-release-sbom.yml@e5f4689e213becd11a05cc08c5ad666b6d515c7c #saml-test-integrations/sbom-test/.github/workflows/syft-release-sbom.yml@main
    with:
      sbom_name: ${{ github.event.release.tag_name || github.ref_name || 'manual' }}