name: syft-sbom-ci

on:
  release:
    types: [published]

permissions:
  actions: read
  contents: write

jobs:
  sbom:
    uses: saml-test-integrations/sbom-test/.github/workflows/syft-release-sbom.yml@main
    with:
      sbom_name: ${{ github.event.release.tag_name }}